"""initial schema

Revision ID: 989de3f24186
Revises: 
Create Date: 2026-05-18 02:41:39.822853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989de3f24186'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_pages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notion_page_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('notion_path', sa.Text(), nullable=False),
    sa.Column('last_edited_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notion_pages_notion_page_id'), 'notion_pages', ['notion_page_id'], unique=True)
    op.create_table('source_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_display_name', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_content_hash'), 'source_documents', ['content_hash'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_type'), 'workflow_runs', ['workflow_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_run_id', sa.BigInteger(), nullable=True),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event'), 'audit_logs', ['event'], unique=False)
    op.create_table('change_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('target_notion_page_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('proposal_json', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_notion_page_id'], ['notion_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_status'), 'change_requests', ['status'], unique=False)
    op.create_table('notion_blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notion_block_id', sa.String(length=128), nullable=False),
    sa.Column('notion_page_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_block_id', sa.BigInteger(), nullable=True),
    sa.Column('block_type', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('block_path', sa.Text(), nullable=True),
    sa.Column('block_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['notion_page_id'], ['notion_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_block_id'], ['notion_blocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notion_blocks_notion_block_id'), 'notion_blocks', ['notion_block_id'], unique=True)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('notion_block_id', sa.BigInteger(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('notion_path', sa.Text(), nullable=True),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['notion_block_id'], ['notion_blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_notion_blocks_notion_block_id'), table_name='notion_blocks')
    op.drop_table('notion_blocks')
    op.drop_index(op.f('ix_change_requests_status'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_audit_logs_event'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workflow_runs_workflow_type'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_source_documents_content_hash'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_notion_pages_notion_page_id'), table_name='notion_pages')
    op.drop_table('notion_pages')
    # ### end Alembic commands ###
