"""Shared bounded text limits for parsed supplement proposals."""

MAX_SUPPLEMENT_TITLE_CHARS = 240
MAX_SUPPLEMENT_SUMMARY_CHARS = 2400
MAX_SUPPLEMENT_CONCEPT_CHARS = 180
MAX_SUPPLEMENT_NOTE_CHARS = 1400
MAX_SUPPLEMENT_CONCEPTS = 30
MAX_SUPPLEMENT_NOTES = 12
MAX_SUPPLEMENT_TOTAL_TEXT_CHARS = 16000
